### ISSUE TITLE
CPU load ?

### ISSUE THREAD

**Issue by zigster64** [Luukdegram/apple_pie#23]
Just running the basic example, Im seeing 100% CPU on 1 core.

??  Not sure if I have configured something wrong, or if Im on a particularly bad release of zig-master with a broken std.net.

Anyway - ApplePie is idling in `var connection = stream.accept() catch |err| switch (err) {`  in src/server.zig ... so that suggest that zig std.net is eating all the CPU.

Curious, will have a deeper play tomorrow.

**Comment by zigster64** [comment]
followup - tried with different build options (as this is actually a benchmarking exersize comparing output to Go / Crystal / Rust)

When built with -Drelease-fast=true ... the benchmarking results using siege are absurdly good compared to regular debug build (which is slightly better than Go / Crystal)

Wasnt expecting that.  (fast build has about 1% of the error rate, and is report 10x the transactions processed - weird !)

**Comment by zigster64** [comment]
Cancel that - I tried the same with https://github.com/Vexu/routez and go the exact same results

... 100% CPU on 1 core when waiting for socket connections through zig std.net
... massive benchmark improvement when building with -Drelease-fast=true

So the "problem" - if there is one - is higher up the chain.  Nothing to do with ApplePie

closing

**Comment by Luukdegram** [comment]
Hi @zigster64, Thank you for reporting this nonetheless.
`accept()` should be a blocking call (theoretically) but it isn't atm. Currently, there are quite some issues upstream with regards to the event loop and I believe there's an idea to improve it soon, but I'm not sure what the exact details of those are. Just wanted to let you know :)

**Comment by zigster64** [comment]
https://github.com/ziglang/zig/issues/8224  is on the radar now  :)
