### ISSUE TITLE
`Status` is not exposed

### ISSUE THREAD

**Issue by Luukdegram** [Luukdegram/apple_pie#42]
Currently, we only expose `Response` from `response.zig`.
This means users cannot use the `Status` type definition anywhere.

There's 2 solutions to this:
- Expose `response.zig` in its entirety.
- Expose `Status` in addition to `Response`

**Comment by nektro** [comment]
would converting `response.zig` to use top level fields like `Request.zig` be an acceptable solution for this?

**Comment by Luukdegram** [comment]
Yes, that would be a good solution.
