### ISSUE TITLE
Pull parameters from handler fn

### ISSUE THREAD

**Issue by leroycep** [Luukdegram/apple_pie#79]
Instead of this:

```zig
const std = @import("std");
const http = @import("apple_pie");

pub const io_mode = .evented;

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const builder = router.Builder(void);

    try http.listenAndServe(
        allocator,
        try std.net.Address.parseIp("127.0.0.1", 8080),
        {},
        comptime router.Router(void, &.{
            builder.get("/hello/:name", []const u8, hello),
        }),
    );
}

/// Shows "Hello {name}" where {name} is /hello/:name
fn hello(_: void, resp: *http.Response, req: http.Request, captures: ?*const anyopaque) !void {
    _ = req;
    const name = @ptrCast(
        *const []const u8,
        @alignCast(
            @alignOf(*const []const u8),
            captures,
        ),
    );
    try resp.writer().print("Hello {s}\n", .{name.*});
}
```

The parameters would be extracted from the function.

```zig
const std = @import("std");
const http = @import("apple_pie");

pub const io_mode = .evented;

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const builder = router.Builder(void);

    try http.listenAndServe(
        allocator,
        try std.net.Address.parseIp("127.0.0.1", 8080),
        {},
        comptime router.Router(void, &.{
            builder.get("/hello/:name", hello),
        }),
    );
}

/// Shows "Hello {name}" where {name} is /hello/:name
fn hello(_: void, resp: *http.Response, req: http.Request, name: []const u8) !void {
    _ = req;
    try resp.writer().print("Hello {s}\n", .{name});
}
```

Not sure if it should match the url parameters by name or position.

Would throw an error if the names/number of url matches is not the same as the number of parameters.

I'm interested in creating a prototype for this.

**Comment by Luukdegram** [comment]
This is actually how the router used to work prior to 5399084b774a609b6058b700ee5777f5d4376733. However, with the removal of `anytype` fields on structs, that implementation was no longer possible as we cannot store different function signatures using the same field. I 100% agree that the current approach is error-prone, unfriendly to use, and hacky. So if this is something you're willing to improve, I'm happy to support you. 

The current idea I had in my head was to introduce some sort of `Captures` struct which contains a reference to all the capture strings, which at least makes the type consistent and we don't need any generics to store the function handler. This was just an idea floating in my head, so I'm looking forward to what you have in mind.
